##__START_INSTALL
CREATE TABLE `##__DB_PREFIX_##__TABLE_NAME` (
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user` varchar(128) DEFAULT NULL,
  `action` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
##__END_INSTALL